// Package config resolves jade's layered configuration: built-in role defaults,
// then the active profile, then the user's local config. Nothing personal is
// compiled into the binary — machine-specific values live in ~/.config/jade.
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Role names an agent's job in the pipeline. Each role carries its own model
// and effort defaults, overridable per unit of work in an issue's YAML block.
type Role string

const (
	RoleDiscovery    Role = "discovery"
	RolePlanning     Role = "planning"
	RoleOrchestrator Role = "orchestrator"
	RoleBuilder      Role = "builder"
	RoleCodeReview   Role = "code_review"
	RoleSecReview    Role = "security_review"
)

// SinkRepo is the discovery_sink value meaning "write into docs/discovery/ of
// the repo being worked on" rather than an external notes directory.
const SinkRepo = "repo"

// Agent is the model configuration for a single role.
type Agent struct {
	Vendor string `yaml:"vendor"`
	Model  string `yaml:"model"`
	Effort string `yaml:"effort"`
}

// Profile captures what differs between machines: which git host is reachable,
// which vendors are permitted, and where discovery notes are written.
type Profile struct {
	Name string `yaml:"name"`
	// GitHost is the issue/PR backend. Only "github" is implemented today.
	GitHost string `yaml:"git_host"`
	// DiscoverySink is where discovery notes land: an absolute path to an
	// Obsidian vault folder, or the literal "repo" to write into
	// docs/discovery/ of the repo being worked on.
	DiscoverySink string `yaml:"discovery_sink"`
	// AllowedVendors gates which agent vendors may be dispatched here.
	AllowedVendors []string `yaml:"allowed_vendors"`
	// Agents overrides the built-in role defaults for this machine.
	Agents map[Role]Agent `yaml:"agents,omitempty"`
	// ProtectedPaths are globs that force a human gate regardless of a unit's
	// autonomy level. Empty means jade's built-in defaults.
	ProtectedPaths []string `yaml:"protected_paths,omitempty"`
	// AgentArgs are native flags passed to a role's agent CLI, after "--".
	//
	// This is a profile concern rather than a per-unit one: it describes the
	// trust posture of a machine, not a property of a piece of work. A unit of
	// work must not be able to widen the permissions it runs under.
	//
	// It is empty by default. An unattended builder needs whatever flag its
	// vendor uses to skip interactive approval, or it will sit at a dialog
	// jade deliberately refuses to answer — but that has to be a decision
	// someone makes for a machine, not a default jade ships.
	AgentArgs map[Role][]string `yaml:"agent_args,omitempty"`
}

// Config is the user's local configuration, generated by `jade init` and never
// committed.
type Config struct {
	ActiveProfile string    `yaml:"active_profile"`
	RepoRoot      string    `yaml:"repo_root"`
	Profiles      []Profile `yaml:"profiles"`
}

// DefaultAgents are the role defaults established during discovery: pay for
// thinking, economize on execution, and never cheap out on security review.
func DefaultAgents() map[Role]Agent {
	return map[Role]Agent{
		RoleDiscovery:    {Vendor: "claude", Model: "opus", Effort: "high"},
		RolePlanning:     {Vendor: "claude", Model: "opus", Effort: "high"},
		RoleOrchestrator: {Vendor: "claude", Model: "sonnet", Effort: "medium"},
		RoleBuilder:      {Vendor: "claude", Model: "sonnet", Effort: "medium"},
		RoleCodeReview:   {Vendor: "claude", Model: "sonnet", Effort: "medium"},
		RoleSecReview:    {Vendor: "claude", Model: "opus", Effort: "high"},
	}
}

// ReadFile parses a config file from disk.
func ReadFile(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no config at %s (run: jade init)", path)
		}
		return nil, err
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return &cfg, nil
}

// Dir returns the directory holding config.yml and any prompt overrides,
// honoring XDG_CONFIG_HOME.
func Dir() (string, error) {
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		base = filepath.Join(home, ".config")
	}
	return filepath.Join(base, "jade"), nil
}

// Path returns the location of the local config file.
func Path() (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "config.yml"), nil
}
