// Package config resolves jade's layered configuration: built-in role defaults,
// then the active profile, then the user's local config. Nothing personal is
// compiled into the binary — machine-specific values live in ~/.config/jade.
package config

import (
	"os"
	"path/filepath"
)

// Role names an agent's job in the pipeline. Each role carries its own model
// and effort defaults, overridable per unit of work in an issue's YAML block.
type Role string

const (
	RoleDiscovery    Role = "discovery"
	RolePlanning     Role = "planning"
	RoleOrchestrator Role = "orchestrator"
	RoleBuilder      Role = "builder"
	RoleCodeReview   Role = "code_review"
	RoleSecReview    Role = "security_review"
)

// Agent is the model configuration for a single role.
type Agent struct {
	Vendor string `yaml:"vendor"`
	Model  string `yaml:"model"`
	Effort string `yaml:"effort"`
}

// Profile captures what differs between machines: which git host is reachable,
// which vendors are permitted, and where discovery notes are written.
type Profile struct {
	Name string `yaml:"name"`
	// GitHost is the issue/PR backend. Only "github" is implemented today.
	GitHost string `yaml:"git_host"`
	// DiscoverySink is where discovery notes land: an absolute path to an
	// Obsidian vault folder, or the literal "repo" to write into
	// docs/discovery/ of the repo being worked on.
	DiscoverySink string `yaml:"discovery_sink"`
	// AllowedVendors gates which agent vendors may be dispatched here.
	AllowedVendors []string `yaml:"allowed_vendors"`
	// Agents overrides the built-in role defaults for this machine.
	Agents map[Role]Agent `yaml:"agents,omitempty"`
}

// Config is the user's local configuration, generated by `jade init` and never
// committed.
type Config struct {
	ActiveProfile string    `yaml:"active_profile"`
	RepoRoot      string    `yaml:"repo_root"`
	Profiles      []Profile `yaml:"profiles"`
}

// DefaultAgents are the role defaults established during discovery: pay for
// thinking, economize on execution, and never cheap out on security review.
func DefaultAgents() map[Role]Agent {
	return map[Role]Agent{
		RoleDiscovery:    {Vendor: "claude", Model: "opus", Effort: "high"},
		RolePlanning:     {Vendor: "claude", Model: "opus", Effort: "high"},
		RoleOrchestrator: {Vendor: "claude", Model: "sonnet", Effort: "medium"},
		RoleBuilder:      {Vendor: "claude", Model: "sonnet", Effort: "medium"},
		RoleCodeReview:   {Vendor: "claude", Model: "sonnet", Effort: "medium"},
		RoleSecReview:    {Vendor: "claude", Model: "opus", Effort: "high"},
	}
}

// Dir returns the directory holding config.yml and any prompt overrides,
// honoring XDG_CONFIG_HOME.
func Dir() (string, error) {
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		base = filepath.Join(home, ".config")
	}
	return filepath.Join(base, "jade"), nil
}

// Path returns the location of the local config file.
func Path() (string, error) {
	dir, err := Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "config.yml"), nil
}
